/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as FormationRouteImport } from './routes/formation'
import { Route as FormateursRouteImport } from './routes/formateurs'
import { Route as AcademieRouteImport } from './routes/academie'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormationSlugRouteImport } from './routes/formation.$slug'

const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationRoute = FormationRouteImport.update({
  id: '/formation',
  path: '/formation',
  getParentRoute: () => rootRouteImport,
} as any)
const FormateursRoute = FormateursRouteImport.update({
  id: '/formateurs',
  path: '/formateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademieRoute = AcademieRouteImport.update({
  id: '/academie',
  path: '/academie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationSlugRoute = FormationSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FormationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academie': typeof AcademieRoute
  '/formateurs': typeof FormateursRoute
  '/formation': typeof FormationRouteWithChildren
  '/programme': typeof ProgrammeRoute
  '/realisations': typeof RealisationsRoute
  '/formation/$slug': typeof FormationSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academie': typeof AcademieRoute
  '/formateurs': typeof FormateursRoute
  '/formation': typeof FormationRouteWithChildren
  '/programme': typeof ProgrammeRoute
  '/realisations': typeof RealisationsRoute
  '/formation/$slug': typeof FormationSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academie': typeof AcademieRoute
  '/formateurs': typeof FormateursRoute
  '/formation': typeof FormationRouteWithChildren
  '/programme': typeof ProgrammeRoute
  '/realisations': typeof RealisationsRoute
  '/formation/$slug': typeof FormationSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academie'
    | '/formateurs'
    | '/formation'
    | '/programme'
    | '/realisations'
    | '/formation/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academie'
    | '/formateurs'
    | '/formation'
    | '/programme'
    | '/realisations'
    | '/formation/$slug'
  id:
    | '__root__'
    | '/'
    | '/academie'
    | '/formateurs'
    | '/formation'
    | '/programme'
    | '/realisations'
    | '/formation/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademieRoute: typeof AcademieRoute
  FormateursRoute: typeof FormateursRoute
  FormationRoute: typeof FormationRouteWithChildren
  ProgrammeRoute: typeof ProgrammeRoute
  RealisationsRoute: typeof RealisationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation': {
      id: '/formation'
      path: '/formation'
      fullPath: '/formation'
      preLoaderRoute: typeof FormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formateurs': {
      id: '/formateurs'
      path: '/formateurs'
      fullPath: '/formateurs'
      preLoaderRoute: typeof FormateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academie': {
      id: '/academie'
      path: '/academie'
      fullPath: '/academie'
      preLoaderRoute: typeof AcademieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/$slug': {
      id: '/formation/$slug'
      path: '/$slug'
      fullPath: '/formation/$slug'
      preLoaderRoute: typeof FormationSlugRouteImport
      parentRoute: typeof FormationRoute
    }
  }
}

interface FormationRouteChildren {
  FormationSlugRoute: typeof FormationSlugRoute
}

const FormationRouteChildren: FormationRouteChildren = {
  FormationSlugRoute: FormationSlugRoute,
}

const FormationRouteWithChildren = FormationRoute._addFileChildren(
  FormationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademieRoute: AcademieRoute,
  FormateursRoute: FormateursRoute,
  FormationRoute: FormationRouteWithChildren,
  ProgrammeRoute: ProgrammeRoute,
  RealisationsRoute: RealisationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
